"""Hawcx OIDC demo relying party.

A minimal Flask app that signs a user in via Hawcx's OIDC /authorize flow,
exchanges the auth code at /oauth2/token, verifies the id_token against
Hawcx's published JWKS, and renders the resulting claims.

What this demo proves:
    1. Hawcx's /authorize endpoint behaves like a standards-compliant OIDC OP
       to a stock RP library (authlib): PKCE works, state/nonce round-trip
       through, redirect_uri exact-match enforcement engages.
    2. The id_token from /oauth2/token verifies cleanly against the discovery
       document + JWKS — no Hawcx-specific tooling required to validate.
    3. Claims (sub, email, email_verified, amr, auth_time, etc.) arrive in
       the standards-mandated locations and shapes.

What's NOT standards-compliant (and the demo papers over):
    Hawcx's /oauth2/token sits behind Kong's key-auth plugin and identifies
    the tenant from the `x-config-id` header (Kong API key), NOT from a
    `client_id` form field. A stock OIDC library would never send that
    header, so the demo injects it explicitly. In a fully spec-compliant
    deployment the token endpoint would be public (no Kong key) and the
    client_id form field would identify the tenant.

Configuration: see .env.example. Run with `python app.py`.
"""

from __future__ import annotations

import json
import os
import secrets
import time
from typing import Any, Dict, Optional

import requests
from authlib.integrations.requests_client import OAuth2Session
from authlib.jose import JsonWebKey, jwt
from authlib.jose.errors import JoseError
from authlib.oauth2.rfc7636 import create_s256_code_challenge
from dotenv import load_dotenv
from flask import Flask, redirect, render_template_string, request, session, url_for

load_dotenv()


def _required_env(name: str) -> str:
    v = os.environ.get(name)
    if not v:
        raise RuntimeError(
            f"Missing required env var: {name}. See .env.example."
        )
    return v


def _build_client_assertion(
    *,
    client_id: str,
    token_endpoint: str,
    issuer: str,
    private_key_path: str,
    kid: str,
    lifetime_seconds: int = 60,
) -> str:
    """Build an RFC 7523 client_assertion JWT signed with the RP's Ed25519 key.

    Claims follow OIDC Core §9 / RFC 7523 §3 exactly:
      iss = sub = client_id
      aud = token_endpoint (we accept either token_endpoint or issuer on
            the OP side; we pick token_endpoint here for compatibility with
            stock OIDC libraries that default to it)
      iat / exp = short window (60s by default; OP caps at 120s)
      jti = single-use nonce; OP rejects replays via Redis SET NX

    The private key is a PEM (PKCS#8) on disk, generated by
    scripts/gen-rp-keypair.py. authlib's :meth:`JsonWebKey.import_key` reads
    the PEM directly; we don't pre-parse it.
    """
    with open(private_key_path, "rb") as f:
        private_key_pem = f.read()
    now = int(time.time())
    claims = {
        "iss": client_id,
        "sub": client_id,
        "aud": token_endpoint,
        "iat": now,
        "exp": now + lifetime_seconds,
        "jti": secrets.token_urlsafe(16),
    }
    header = {"alg": "EdDSA", "typ": "JWT", "kid": kid}
    # authlib's jwt.encode returns bytes; the token-endpoint POST expects str.
    encoded = jwt.encode(header, claims, private_key_pem)
    return encoded.decode("ascii") if isinstance(encoded, bytes) else encoded


# --- Config ----------------------------------------------------------------
# OIDC_ISSUER must byte-match the `iss` claim in the id_token and the issuer
# field in the discovery doc. Trailing slashes matter — keep it clean.
OIDC_ISSUER = _required_env("HAWCX_OIDC_ISSUER").rstrip("/")
# CLIENT_ID is the Hawcx project UUID (the value Kong's consumer key resolves
# to under the hood). It's also the `aud` claim in the id_token.
CLIENT_ID = _required_env("HAWCX_CLIENT_ID")
# CONFIG_ID is the Kong x-config-id header value — a per-project SDK key.
# Used because Hawcx's /oauth2/token is behind key-auth (see module docstring).
CONFIG_ID = _required_env("HAWCX_CONFIG_ID")
REDIRECT_URI = os.environ.get("REDIRECT_URI", "http://localhost:5000/callback")
APP_PORT = int(os.environ.get("PORT", "5000"))
# SDK config id passed to /authorize as a query param so Hawcx's hosted login
# UI knows which Kong key its JS should use when calling /v1/auth. The OP
# forwards it to /login; if the OP later persists it on oauth_config, this
# becomes unnecessary. Defaults to the same CONFIG_ID — the demo uses one
# project for both the RP role and the login-UI's hx_auth calls.
SDK_CONFIG_ID = os.environ.get("HAWCX_SDK_CONFIG_ID", CONFIG_ID)

# --- Client-authentication profiles ----------------------------------------
# The demo can authenticate as either of two OIDC clients, picked at runtime
# via a UI switch on the landing page (carried through the flow in the Flask
# session). The OP pins the authentication method PER CLIENT, so each profile
# is a distinct client_id — you cannot send a private_key_jwt assertion as the
# public client (the OP rejects it; that's the downgrade defense).
#
#   * Public profile  — HAWCX_CLIENT_ID, token_endpoint_auth_method=none.
#                       Always available; PKCE is the only secret.
#   * Confidential    — HAWCX_CONFIDENTIAL_CLIENT_ID + a PEM private key +
#                       its kid, token_endpoint_auth_method=private_key_jwt.
#                       Only offered when all three are configured.
#
# HAWCX_AUTH_METHOD remains as the *default* selection for the plain "Sign in"
# entry point (backward compatible); the UI buttons pass ?method= explicitly.
DEFAULT_AUTH_METHOD = os.environ.get("HAWCX_AUTH_METHOD", "none").lower()
if DEFAULT_AUTH_METHOD not in ("none", "private_key_jwt"):
    raise RuntimeError(
        f"HAWCX_AUTH_METHOD must be 'none' or 'private_key_jwt' (got {DEFAULT_AUTH_METHOD!r})"
    )

CONFIDENTIAL_CLIENT_ID = os.environ.get("HAWCX_CONFIDENTIAL_CLIENT_ID")
HAWCX_PRIVATE_KEY_PATH = os.environ.get("HAWCX_PRIVATE_KEY_PATH")
HAWCX_PRIVATE_KEY_KID = os.environ.get("HAWCX_PRIVATE_KEY_KID")

# The confidential option is available iff a key + kid are configured AND the
# key file actually exists on disk. The client_id falls back to HAWCX_CLIENT_ID
# when HAWCX_CONFIDENTIAL_CLIENT_ID is unset — supports the single-client
# layout where the same project row is registered as private_key_jwt.
CONFIDENTIAL_AVAILABLE = bool(
    HAWCX_PRIVATE_KEY_PATH
    and HAWCX_PRIVATE_KEY_KID
    and os.path.isfile(HAWCX_PRIVATE_KEY_PATH)
)


def _resolve_profile(method: str) -> Dict[str, Any]:
    """Map a requested method to its (client_id, key, kid) profile.

    Raises ValueError if private_key_jwt is requested but not configured —
    the caller (``/login``) surfaces this as a friendly error rather than
    letting the flow start with a half-configured profile.
    """
    if method == "private_key_jwt":
        if not CONFIDENTIAL_AVAILABLE:
            raise ValueError(
                "private_key_jwt is not configured. Set HAWCX_PRIVATE_KEY_PATH + "
                "HAWCX_PRIVATE_KEY_KID (and optionally HAWCX_CONFIDENTIAL_CLIENT_ID), "
                "and ensure the key file exists. See scripts/gen-rp-keypair.py."
            )
        return {
            "method": "private_key_jwt",
            "client_id": CONFIDENTIAL_CLIENT_ID or CLIENT_ID,
            "private_key_path": HAWCX_PRIVATE_KEY_PATH,
            "kid": HAWCX_PRIVATE_KEY_KID,
        }
    return {
        "method": "none",
        "client_id": CLIENT_ID,
        "private_key_path": None,
        "kid": None,
    }


app = Flask(__name__)
# In production this would come from a secret manager. The demo regenerates
# on every restart, which logs out any existing sessions — fine for a demo.
app.secret_key = os.environ.get("FLASK_SECRET", secrets.token_urlsafe(32))


# --- One-shot discovery + JWKS load ----------------------------------------
# Fetched at startup to keep request paths fast. A production RP would:
#   - retry on transient failures here
#   - re-fetch JWKS on a JWT `kid` miss (key rotation)
# Both are out of scope for a demo.

_discovery = requests.get(
    f"{OIDC_ISSUER}/.well-known/openid-configuration", timeout=10
).json()
_jwks = JsonWebKey.import_key_set(
    requests.get(_discovery["jwks_uri"], timeout=10).json()
)

# Sanity-check at boot rather than at first sign-in.
assert (
    _discovery.get("authorization_endpoint")
    and _discovery.get("token_endpoint")
), "Discovery doc missing required endpoints — wrong issuer?"


# --- Routes ----------------------------------------------------------------


######################################################################
# Templates
#
# The visual style here is deliberately a "real product" — emerald
# accent, full-page product layout, branded header — distinct from the
# Hawcx login UI's blue-on-white centered card. Stops audiences during
# demos asking "wait, am I still on the same site?"
#
# Fictional brand: "Acme Notes" — a notes-taking SaaS. Familiar product
# category, makes a Welcome-back-here-are-your-notes dashboard obvious
# without needing real backing data.
######################################################################

# Shared CSS for both pages — defined once, injected via Jinja so the
# headers/footers stay byte-identical.
_SHARED_CSS = """
:root {
  --bg: #fafaf9;
  --surface: #ffffff;
  --border: #e7e5e4;
  --ink: #18181b;
  --ink-muted: #71717a;
  --ink-faint: #a1a1aa;
  --brand: #059669;
  --brand-dark: #047857;
  --brand-tint: #ecfdf5;
  --brand-ink: #064e3b;
  --danger-bg: #fef2f2;
  --danger-ink: #991b1b;
  --shadow-sm: 0 1px 2px rgba(0,0,0,.04);
  --shadow-md: 0 1px 3px rgba(0,0,0,.04), 0 4px 12px rgba(0,0,0,.04);
  --shadow-lg: 0 1px 3px rgba(0,0,0,.04), 0 24px 48px rgba(0,0,0,.06);
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; }
body {
  font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
  background: var(--bg);
  color: var(--ink);
  font-size: 15px;
  line-height: 1.5;
  min-height: 100vh;
}
a { color: var(--brand-dark); text-decoration: none; }
a:hover { text-decoration: underline; }
code { font-family: ui-monospace, "SF Mono", Menlo, monospace; font-size: 12px; }

/* ── Top nav ── */
.nav {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 14px 32px;
  border-bottom: 1px solid var(--border);
  background: var(--surface);
}
.brand { display: flex; align-items: center; gap: 10px; font-weight: 600; font-size: 16px; }
.brand-mark {
  width: 28px; height: 28px;
  border-radius: 7px;
  background: linear-gradient(135deg, var(--brand) 0%, var(--brand-dark) 100%);
  color: #fff;
  display: inline-flex; align-items: center; justify-content: center;
  font-weight: 700; font-size: 14px;
}
.nav-right { display: flex; align-items: center; gap: 16px; }
.nav-link { color: var(--ink-muted); font-size: 14px; font-weight: 500; }
.nav-link:hover { color: var(--ink); text-decoration: none; }

/* ── Buttons ── */
.btn {
  display: inline-flex; align-items: center; justify-content: center; gap: 6px;
  padding: 9px 18px;
  border: none; border-radius: 8px;
  font-family: inherit; font-size: 14px; font-weight: 500;
  cursor: pointer; text-decoration: none;
  transition: background .15s, transform .05s;
}
.btn:hover { text-decoration: none; }
.btn:active { transform: translateY(1px); }
.btn-primary { background: var(--brand); color: #fff; }
.btn-primary:hover { background: var(--brand-dark); }
.btn-ghost { background: transparent; color: var(--ink); border: 1px solid var(--border); }
.btn-ghost:hover { background: var(--bg); color: var(--ink); }
.btn-lg { padding: 12px 24px; font-size: 15px; }

/* ── Generic surfaces ── */
.container { max-width: 1080px; margin: 0 auto; padding: 0 32px; }
.panel {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  box-shadow: var(--shadow-sm);
}
.panel-header {
  display: flex; align-items: center; justify-content: space-between;
  padding: 18px 24px;
  border-bottom: 1px solid var(--border);
}
.panel-header h2 {
  margin: 0; font-size: 15px; font-weight: 600;
}
.panel-body { padding: 20px 24px; }

/* ── Hero (landing) ── */
.hero {
  padding: 96px 32px 64px;
  text-align: center;
}
.hero h1 {
  margin: 0 0 16px;
  font-size: 44px;
  font-weight: 700;
  letter-spacing: -0.02em;
  line-height: 1.1;
}
.hero h1 .accent {
  background: linear-gradient(135deg, var(--brand) 0%, var(--brand-dark) 100%);
  -webkit-background-clip: text; background-clip: text;
  color: transparent;
}
.hero p {
  margin: 0 auto 32px;
  max-width: 540px;
  color: var(--ink-muted);
  font-size: 17px;
}
.hero .cta-row { display: flex; gap: 12px; justify-content: center; }

/* ── Features ── */
.features { padding: 0 32px 80px; }
.feature-grid {
  display: grid; grid-template-columns: repeat(3, 1fr); gap: 20px;
  max-width: 1080px; margin: 0 auto;
}
.feature {
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 12px;
  padding: 24px;
}
.feature-icon {
  width: 38px; height: 38px; border-radius: 8px;
  background: var(--brand-tint); color: var(--brand-dark);
  display: inline-flex; align-items: center; justify-content: center;
  font-size: 18px; margin-bottom: 14px;
}
.feature h3 { margin: 0 0 6px; font-size: 15px; }
.feature p { margin: 0; color: var(--ink-muted); font-size: 13px; line-height: 1.5; }

/* ── Footer ── */
footer {
  text-align: center;
  padding: 32px;
  border-top: 1px solid var(--border);
  color: var(--ink-faint);
  font-size: 12px;
}
footer .secured { display: inline-flex; align-items: center; gap: 6px; }
footer .secured .lock { font-size: 11px; }

/* ── Dashboard ── */
.dashboard { padding: 32px 32px 80px; }
.dashboard h1 {
  margin: 0 0 4px; font-size: 24px; font-weight: 600; letter-spacing: -0.01em;
}
.dashboard .sub { margin: 0 0 28px; color: var(--ink-muted); font-size: 14px; }
.grid-2 { display: grid; grid-template-columns: 1fr 360px; gap: 20px; }
@media (max-width: 880px) { .grid-2 { grid-template-columns: 1fr; } }

/* ── User chip in nav ── */
.user-chip {
  display: inline-flex; align-items: center; gap: 8px;
  padding: 6px 12px 6px 6px;
  border: 1px solid var(--border); border-radius: 999px;
  font-size: 13px; color: var(--ink);
}
.avatar {
  width: 26px; height: 26px; border-radius: 50%;
  background: linear-gradient(135deg, #34d399, #059669);
  display: inline-flex; align-items: center; justify-content: center;
  color: #fff; font-weight: 600; font-size: 12px;
}

/* ── Notes list (fictional) ── */
.note-item {
  display: flex; align-items: center; gap: 14px;
  padding: 14px 24px;
  border-top: 1px solid var(--border);
}
.note-item:first-child { border-top: none; }
.note-icon {
  width: 32px; height: 32px; border-radius: 8px;
  background: var(--brand-tint);
  display: inline-flex; align-items: center; justify-content: center;
  font-size: 14px;
}
.note-title { flex: 1; font-size: 14px; font-weight: 500; }
.note-time { color: var(--ink-faint); font-size: 12px; font-family: ui-monospace, monospace; }

/* ── Auth panel + claim dump ── */
.verified-pill {
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--brand-tint);
  color: var(--brand-ink);
  padding: 4px 10px;
  border-radius: 999px;
  font-size: 11px; font-weight: 500;
}
.auth-fact { display: flex; gap: 10px; padding: 10px 0; font-size: 13px; color: var(--ink-muted); }
.auth-fact strong { color: var(--ink); font-weight: 500; }
.auth-fact .check { color: var(--brand); font-weight: 700; }
.claims-toggle {
  display: inline-flex; align-items: center; gap: 6px;
  background: var(--bg); border: 1px solid var(--border);
  padding: 8px 12px; border-radius: 8px;
  font-size: 12px; color: var(--ink); cursor: pointer;
  width: 100%; justify-content: space-between;
  font-family: inherit;
}
.claims-toggle:hover { background: #f5f5f4; }
.claims-toggle .chev { transition: transform .15s; }
.claims[open] .claims-toggle .chev { transform: rotate(90deg); }
.claims-dump {
  background: #0c0a09; color: #e7e5e4;
  padding: 16px;
  border-radius: 8px;
  font-family: ui-monospace, "SF Mono", Menlo, monospace;
  font-size: 11.5px; line-height: 1.7;
  overflow-x: auto;
  margin-top: 12px;
}
.claims-dump .k { color: #6ee7b7; }
.claims-dump .v { color: #fde68a; }

.config-strip {
  display: flex; flex-wrap: wrap; gap: 8px 24px;
  padding: 14px 24px;
  border-top: 1px solid var(--border);
  font-family: ui-monospace, monospace; font-size: 11px; color: var(--ink-faint);
}
.config-strip strong { color: var(--ink-muted); font-weight: 500; }
"""


# Reusable nav strip — emoji "logo" + brand text, optional right-side slot.
_NAV_LANDING = """
<nav class="nav">
  <div class="brand"><span class="brand-mark">A</span> Acme Notes</div>
  <div class="nav-right">
    <a class="nav-link" href="#">Pricing</a>
    <a class="nav-link" href="#">Docs</a>
    <a class="btn btn-primary" href="{{ url_for('login') }}">Sign in</a>
  </div>
</nav>
"""


_NAV_DASHBOARD = """
<nav class="nav">
  <div class="brand"><span class="brand-mark">A</span> Acme Notes</div>
  <div class="nav-right">
    <a class="nav-link" href="#">My notes</a>
    <a class="nav-link" href="#">Workspaces</a>
    <span class="user-chip">
      <span class="avatar">{{ (claims.get('email') or claims['sub'])[:1] | upper }}</span>
      {{ claims.get('email') or claims['sub'] }}
    </span>
    <a class="btn btn-ghost" href="{{ url_for('logout') }}">Sign out</a>
  </div>
</nav>
"""


LANDING_HTML = (
    """<!doctype html>
<html><head><meta charset="utf-8">
<title>Acme Notes · Your team's collective brain</title>
<style>""" + _SHARED_CSS + """</style></head><body>
"""
    + _NAV_LANDING
    + """
<section class="hero">
  <h1>Your team's <span class="accent">collective brain</span></h1>
  <p>Notes that sync. Search that actually works. Sign in to pick up where you
     left off — your device is your password.</p>
  <div class="cta-row">
    <a class="btn btn-primary btn-lg" href="{{ url_for('login', method='none') }}">Sign in (public + PKCE) →</a>
    {% if confidential_available %}
    <a class="btn btn-primary btn-lg" href="{{ url_for('login', method='private_key_jwt') }}">Sign in (private_key_jwt) →</a>
    {% endif %}
    <a class="btn btn-ghost btn-lg" href="#features">Learn more</a>
  </div>
  <p class="cta-note">
    {% if confidential_available %}
    Two token-endpoint auth methods are wired up. <b>Public + PKCE</b> uses
    client <code>{{ public_client_id }}</code>; <b>private_key_jwt</b> uses
    client <code>{{ confidential_client_id }}</code> and signs an Ed25519
    assertion. The OP enforces the method per client.
    {% else %}
    Public-client + PKCE flow. Configure HAWCX_PRIVATE_KEY_PATH + KID to
    enable the private_key_jwt option.
    {% endif %}
  </p>
</section>

<section class="features" id="features">
  <div class="feature-grid">
    <div class="feature">
      <div class="feature-icon">✍️</div>
      <h3>Capture anything</h3>
      <p>Markdown, screenshots, voice memos — all in one searchable inbox.</p>
    </div>
    <div class="feature">
      <div class="feature-icon">🔍</div>
      <h3>Search that works</h3>
      <p>Full-text + semantic search across notes, attachments, and links.</p>
    </div>
    <div class="feature">
      <div class="feature-icon">🛡️</div>
      <h3>Passwordless by default</h3>
      <p>Device-bound credentials via Hawcx — no passwords, no SMS codes,
         nothing to phish.</p>
    </div>
  </div>
</section>

<footer>
  <div class="secured">
    <span class="lock">🔒</span>
    Secured by <a href="https://hawcx.com">Hawcx</a> · OIDC RP demo ·
    <code>{{ issuer }}</code>
  </div>
</footer>
</body></html>"""
)


SIGNED_IN_HTML = (
    """<!doctype html>
<html><head><meta charset="utf-8">
<title>My notes · Acme Notes</title>
<style>""" + _SHARED_CSS + """</style></head><body>
"""
    + _NAV_DASHBOARD
    + """
<main class="container dashboard">
  <h1>Welcome back, {{ (claims.get('email') or claims['sub']).split('@')[0] }}.</h1>
  <p class="sub">You haven't opened Acme Notes in a while. Here's where you left off.</p>

  <div class="grid-2">
    <!-- ── Left column: fake notes list ──────────────────── -->
    <div class="panel">
      <div class="panel-header">
        <h2>Recent notes</h2>
        <a class="btn btn-primary" href="#">+ New note</a>
      </div>
      <div>
        <div class="note-item">
          <div class="note-icon">📝</div>
          <div class="note-title">Q3 architecture review notes</div>
          <div class="note-time">2h ago</div>
        </div>
        <div class="note-item">
          <div class="note-icon">📝</div>
          <div class="note-title">Brainstorm: onboarding rewrite</div>
          <div class="note-time">yesterday</div>
        </div>
        <div class="note-item">
          <div class="note-icon">📝</div>
          <div class="note-title">Customer call — Sequinox</div>
          <div class="note-time">3 days ago</div>
        </div>
        <div class="note-item">
          <div class="note-icon">📝</div>
          <div class="note-title">Reading list (offsite)</div>
          <div class="note-time">1 week ago</div>
        </div>
      </div>
    </div>

    <!-- ── Right column: account / proof-of-auth panel ──── -->
    <div class="panel">
      <div class="panel-header">
        <h2>Account</h2>
        <span class="verified-pill">✓ id_token verified</span>
      </div>
      <div class="panel-body">
        <div class="auth-fact">
          <span class="check">✓</span>
          <span><strong>Signed in</strong> as {{ claims.get('email') or claims['sub'] }}</span>
        </div>
        <div class="auth-fact">
          <span class="check">✓</span>
          <span><strong>Device-bound credential</strong> (amr: <code>{{ claims.get('amr', ['?']) | join(', ') }}</code>)</span>
        </div>
        <div class="auth-fact">
          <span class="check">✓</span>
          <span><strong>JWT verified</strong> against the published JWKS</span>
        </div>

        <details class="claims" style="margin-top: 14px;">
          <summary class="claims-toggle">
            <span>Show full id_token claims</span>
            <span class="chev">›</span>
          </summary>
          <div class="claims-dump">
            {% for k, v in claims.items() -%}
            <div><span class="k">{{ k }}</span>: <span class="v">{{ v | tojson }}</span></div>
            {%- endfor %}
          </div>
        </details>
      </div>
      <div class="config-strip">
        <span><strong>iss:</strong> {{ issuer }}</span>
        <span><strong>jwks:</strong> <a href="{{ jwks_uri }}">view</a></span>
      </div>
    </div>
  </div>
</main>

<footer>
  <div class="secured">
    <span class="lock">🔒</span>
    Acme Notes · Authenticated via Hawcx OIDC
  </div>
</footer>
</body></html>"""
)


@app.route("/")
def index():
    if "id_token_claims" in session:
        return render_template_string(
            SIGNED_IN_HTML,
            claims=session["id_token_claims"],
            issuer=OIDC_ISSUER,
            jwks_uri=_discovery["jwks_uri"],
        )
    return render_template_string(
        LANDING_HTML,
        issuer=OIDC_ISSUER,
        client_id=CLIENT_ID,
        redirect_uri=REDIRECT_URI,
        confidential_available=CONFIDENTIAL_AVAILABLE,
        public_client_id=CLIENT_ID,
        confidential_client_id=(CONFIDENTIAL_CLIENT_ID or CLIENT_ID),
    )


@app.route("/login")
def login():
    """Kick off the OIDC code flow.

    The ``?method=`` query param (set by the landing-page buttons) selects
    the client-authentication profile for this flow — ``none`` (public +
    PKCE) or ``private_key_jwt``. The chosen profile's client_id is used at
    /authorize AND stored in the session so /callback exchanges the code as
    the SAME client (the OP pins the method per client_id).

    Generates PKCE verifier+challenge and nonce ourselves rather than
    relying on Authlib's internal PKCE management — the verifier is the
    one thing we MUST round-trip via the Flask session, so making it
    explicit keeps the code path obvious.
    """
    requested_method = (request.args.get("method") or DEFAULT_AUTH_METHOD).lower()
    if requested_method not in ("none", "private_key_jwt"):
        return _err(f"Unknown auth method: {requested_method}"), 400
    try:
        profile = _resolve_profile(requested_method)
    except ValueError as e:
        return _err(str(e)), 400

    # PKCE per RFC 7636. A 32-byte random verifier base64url-encodes to 43
    # chars (well above the spec's 43-char minimum and below the 128-char
    # maximum). create_s256_code_challenge applies SHA-256 + base64url.
    verifier = secrets.token_urlsafe(32)
    challenge = create_s256_code_challenge(verifier)

    # OIDC nonce — round-tripped through the id_token's `nonce` claim and
    # verified in /callback. Defends against id_token replay.
    nonce = secrets.token_urlsafe(16)

    oauth = OAuth2Session(
        client_id=profile["client_id"],
        redirect_uri=REDIRECT_URI,
        scope="openid profile email",
    )
    url, state = oauth.create_authorization_url(
        _discovery["authorization_endpoint"],
        code_challenge=challenge,
        code_challenge_method="S256",
        nonce=nonce,
        # Hawcx-specific: the hosted login UI's JS needs the Kong x-config-id
        # to call /v1/auth. Forwarded as a query param the OP threads through
        # to /login. Drop this once oauth_config.sdk_config_id ships.
        sdk_config_id=SDK_CONFIG_ID,
    )

    session["oauth_state"] = state
    session["oauth_nonce"] = nonce
    session["pkce_verifier"] = verifier
    # Persist the whole profile so /callback authenticates as the same client.
    session["auth_method"] = profile["method"]
    session["auth_client_id"] = profile["client_id"]
    return redirect(url)


@app.route("/callback")
def callback():
    """Receive ?code & ?state, exchange for id_token, verify, render.

    Order of validation is important:
        1. state — defends against CSRF on the redirect
        2. error params — surface OP-side rejections before token exchange
        3. token exchange — needs Kong's x-config-id header, plus PKCE
        4. id_token signature — JWKS verification
        5. id_token claims — iss / aud / exp / nbf / nonce
    """
    expected_state = session.pop("oauth_state", None)
    expected_nonce = session.pop("oauth_nonce", None)
    verifier = session.pop("pkce_verifier", None)
    # Profile chosen at /login. Defaults preserve behaviour for any in-flight
    # session that predates the switch (treat as public client).
    auth_method = session.pop("auth_method", DEFAULT_AUTH_METHOD)
    auth_client_id = session.pop("auth_client_id", CLIENT_ID)

    received_state = request.args.get("state")
    if not expected_state or received_state != expected_state:
        return _err("State mismatch — possible CSRF or a stale session"), 400

    if "error" in request.args:
        desc = request.args.get("error_description", "")
        return _err(f"Authorization error: {request.args['error']} — {desc}"), 400

    code = request.args.get("code")
    if not code or not verifier:
        return _err("Missing code or PKCE verifier"), 400

    # --- Token exchange ----------------------------------------------------
    # Two profiles supported:
    #
    # * HAWCX_AUTH_METHOD=none (default): public client + PKCE only —
    #   identical to the original behaviour. client_id goes in the body.
    #
    # * HAWCX_AUTH_METHOD=private_key_jwt: RFC 7523 client_assertion.
    #   The RP signs a short-lived EdDSA JWT with its private key; the
    #   OP verifies against the registered JWKS. PKCE is still required
    #   in this profile (RFC 9700 §2.1.1 — belt + suspenders).
    body: Dict[str, Any] = {
        "code": code,
        "code_verifier": verifier,
        "grant_type": "authorization_code",
        "redirect_uri": REDIRECT_URI,
        "client_id": auth_client_id,
    }
    if auth_method == "private_key_jwt":
        profile = _resolve_profile("private_key_jwt")
        body["client_assertion_type"] = (
            "urn:ietf:params:oauth:client-assertion-type:jwt-bearer"
        )
        body["client_assertion"] = _build_client_assertion(
            client_id=auth_client_id,
            token_endpoint=_discovery["token_endpoint"],
            issuer=OIDC_ISSUER,
            private_key_path=profile["private_key_path"] or "",
            kid=profile["kid"] or "",
        )

    try:
        token_resp = requests.post(
            _discovery["token_endpoint"],
            data=body,
            timeout=15,
        )
    except requests.RequestException as e:
        return _err(f"Network error reaching token endpoint: {e}"), 502

    if not token_resp.ok:
        body = token_resp.text[:500]
        return _err(
            f"Token endpoint returned {token_resp.status_code}: {body}"
        ), 400

    token = token_resp.json()
    id_token = token.get("id_token")
    if not id_token:
        return _err("Token response missing id_token"), 502

    # --- id_token verification --------------------------------------------
    # authlib verifies signature using the JWKS we cached at startup. The
    # claims_options dict tells it which claim values are required and what
    # they must equal — anything mismatched raises a JoseError.
    try:
        claims = jwt.decode(
            id_token,
            _jwks,
            claims_options={
                "iss": {"essential": True, "value": OIDC_ISSUER},
                # aud must equal the client_id we authenticated as for THIS
                # flow (set at /login), not a module-wide default — the two
                # profiles use different client_ids.
                "aud": {"essential": True, "value": auth_client_id},
                "exp": {"essential": True},
                "nonce": {"essential": True, "value": expected_nonce},
            },
        )
        claims.validate()
    except JoseError as e:
        return _err(f"id_token verification failed: {e}"), 400

    # Strip non-serializable fields for the session dict and render.
    session["id_token_claims"] = dict(claims)
    return redirect(url_for("index"))


@app.route("/logout")
def logout():
    """Local logout only — Hawcx doesn't expose an OIDC end_session endpoint."""
    session.clear()
    return redirect(url_for("index"))


def _err(message: str) -> str:
    """Error page that matches the Acme Notes brand chrome."""
    return render_template_string(
        """<!doctype html><html><head><meta charset="utf-8">
        <title>Sign-in failed · Acme Notes</title>
        <style>""" + _SHARED_CSS + """
        .err-wrap { padding: 80px 32px; display: flex; justify-content: center; }
        .err-card { max-width: 520px; width: 100%; }
        .err-card .panel-body { padding: 28px 24px; }
        .err-title { display: flex; align-items: center; gap: 10px;
          font-size: 17px; font-weight: 600; color: var(--danger-ink); margin: 0 0 6px; }
        .err-msg { color: var(--ink-muted); font-size: 14px; margin: 0 0 20px; line-height: 1.55; }
        </style></head><body>""" + _NAV_LANDING + """
        <div class="err-wrap">
          <div class="panel err-card">
            <div class="panel-body">
              <h1 class="err-title">⚠️ Couldn't sign you in</h1>
              <p class="err-msg">{{ message }}</p>
              <a class="btn btn-primary" href="{{ url_for('index') }}">← Back to Acme Notes</a>
            </div>
          </div>
        </div></body></html>""",
        message=message,
    )


if __name__ == "__main__":
    # `threaded=True` so the dev server doesn't deadlock on the discovery
    # fetch at startup if the OIDC OP is slow.
    app.run(host="0.0.0.0", port=APP_PORT, debug=True, threaded=True)
